import assert from "node:assert/strict";
import test from "node:test";

async function render() {
  const workerUrl = new URL("../dist/server/index.js", import.meta.url);
  workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}`);
  const { default: worker } = await import(workerUrl.href);
  return worker.fetch(
    new Request("http://localhost/", { headers: { accept: "text/html", host: "localhost" } }),
    { ASSETS: { fetch: async () => new Response("Not found", { status: 404 }) } },
    { waitUntil() {}, passThroughOnException() {} },
  );
}

test("server renders a personal laboratory before revealing the mystery", async () => {
  const response = await render();
  assert.equal(response.status, 200);
  const html = await response.text();
  assert.match(html, /Lab 17 Interactive Portfolio/i);
  assert.match(html, /Come in.*lab is.*still awake/is);
  assert.match(html, /ENTER LAB 17/);
  assert.match(html, /Wenrui.*Alina.*Wu/i);
  assert.match(html, /This is where Alina Wu keeps algorithms, physical prototypes, research notes, and questions about how systems become understandable and useful to people/);
  assert.doesNotMatch(html, /missing person/i);
  assert.doesNotMatch(html, /[\u4e00-\u9fff]/);
});

test("source contains six room objects, real work, and a progressive reveal", async () => {
  const { readFile } = await import("node:fs/promises");
  const page = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  const contentFiles = ["site","intro","room","computer","references","books","drawer","notebook","board","field-case","fax-contact"];
  const content = (await Promise.all(contentFiles.map((name) => readFile(new URL(`../content/${name}.json`, import.meta.url), "utf8")))).join("\n");
  for (const zone of ["computer", "drawer", "notebook", "books", "board", "fieldcase"]) {
    assert.match(page, new RegExp(`active===\\"${zone}\\"|active!==\\"${zone}\\"|\\"${zone}\\"`));
  }
  assert.match(page, /from "@\/content"/);
  assert.match(content, /ALINA\.OS/);
  assert.match(content, /PROJECTS \/ 3 ITEMS/);
  assert.match(content, /README\.txt/);
  assert.match(content, /LAB_LOG\.md/);
  assert.match(content, /Joining Thermo Fisher Scientific/);
  assert.doesNotMatch(content, /ABOUT\.txt/);
  assert.doesNotMatch(content, /[‘’]/);
  assert.match(page, /lab-log-line/);
  assert.match(content, /USER PROFILE \/ ALINA\.WU/);
  assert.match(page, /os-profile-trigger/);
  assert.match(page, /onToggleMaximize=\{toggleMaximizedWindow\}/);
  assert.match(page, /maximizedWindow===\"references\"/);
  assert.match(page, /window-maximize/);
  assert.match(page, /window-close/);
  assert.match(page, /taskbar-apps/);
  assert.match(page, /taskbarWindows\.map\(\(windowId\)=>/);
  assert.match(page, /taskbarWindowIds\.filter\(showComputerWindow\)/);
  assert.match(page, /label:"REFERENCES"/);
  assert.match(page, /label:"ALLOCATION"/);
  assert.match(page, /computerContent\.sidebar\.references\}<\/button><button onClick=\{\(\) => openComputerFile\(\"lablog\"\)\}/);
  assert.doesNotMatch(page, /computerContent\.sidebar\.readme/);
  assert.match(content, /Quality of Life in Shanghai/);
  assert.match(content, /Automatic and Satisfactory Course Assignment/);
  assert.match(content, /Monitoring Device for Muscle Usage.*Behavior/);
  assert.match(content, /Social Futures Lab/i);
  assert.match(content, /Thermo Fisher Scientific/i);
  assert.match(content, /User has not checked in/i);
  assert.match(content, /Alina Wu has been offline for four days.*This workstation continues to sync/i);
  assert.doesNotMatch(content, /Her computer/);
  assert.doesNotMatch(content, /Why is this appearing on a portfolio computer/);
  assert.doesNotMatch(content, /I am not missing/);
  assert.match(content, /The first wellbeing prototype is ready for feedback/);
  assert.match(content, /FEEDBACK IN PROGRESS/);
  assert.match(content, /awu78@uw\.edu/);
  assert.doesNotMatch(content, /hello@example\.com/);
  assert.match(content, /INCOMING FAX/);
  assert.match(content, /CLICK THE HIGHLIGHTED PRINTER/);
  assert.match(page, /onDoubleClick/);
  assert.doesNotMatch(page, /DOUBLE CLICK TO OPEN/);
  assert.doesNotMatch(page, />DOUBLE CLICK</);
  for (const zone of ["drawer", "books", "notebook", "board", "fieldcase", "printer", "contact"]) {
    assert.match(page, new RegExp(`ZoneCloseup3D zone=\\"${zone}\\"`));
  }
  assert.doesNotMatch(content, /TURN PAGE/);
  assert.doesNotMatch(page, /book-turning-sheet/);
  assert.match(content, /FIELD CASE \/ LIFE OUTSIDE THE LAB/);
  assert.match(content, /WORLD MAP \/ PLACES VISITED/);
  assert.match(content, /RECIPE CARDS \/ COOKING \+ BAKING/);
  assert.match(content, /LASER SHOOTING \/ HIGH SCHOOL TEAM/);
  assert.match(page, /field-map-reading/);
  assert.match(page, /drawFieldCaseMapViewport/);
  assert.doesNotMatch(content, /editable layout markers|Replace prompts and layout pins/);
  assert.match(content, /REFERENCES\.web/);
  assert.match(content, /PERSONAL SHELF \/ BOOKS \+ FILMS/);
  assert.match(content, /LAB 17 \/ PINNED TODO/);
  assert.match(content, /turn the EMG model into an explorable exhibit/);
  assert.match(content, /add a guide who knows the room/);
  assert.match(content, /open richer project evidence/);
  assert.match(content, /show what has been discovered/);
  assert.match(content, /add a visual Version History/);
  assert.match(content, /make every object feel more physical/);
  assert.match(content, /design touch controls for the room/);
  assert.match(content, /BOARD \/ PINNED TODO/);
  assert.doesNotMatch(content, /NOTE BOARD \/ FOLLOW THE THREADS/);
  assert.doesNotMatch(content, /check potential confounders/);
  assert.doesNotMatch(content, /evaluate the whole distribution/);
  assert.doesNotMatch(content, /test the intervention/);
  assert.doesNotMatch(content, /make the workflow legible before changing it/);
  assert.doesNotMatch(content, /BOARD \/ PRINCIPLES/);
  assert.match(content, /"openingEnabled": false/);
  assert.match(content, /"personalDetailsOpeningEnabled": false/);
  assert.match(content, /"comingSoon": "COMING SOON"/);
  assert.match(content, /Whole Brain Living/);
  assert.match(content, /To Live/);
  assert.match(content, /Cries in the Drizzle/);
  assert.match(content, /Keigo Higashino/);
  assert.match(content, /Journey Under the Midnight Sun/);
  assert.match(content, /Farewell My Concubine/);
  assert.doesNotMatch(page, /series:higashino/);
  assert.doesNotMatch(page, /if\(!booksContent\.openingEnabled\)return/);
  assert.doesNotMatch(page, /selectedMovie|dvd-case-detail|dvd-zoom/);
  assert.match(content, /A New Solution to the Random Assignment Problem/);
  assert.match(content, /Simultaneously Achieving Ex-Ante and Ex-Post Fairness/);
  assert.match(content, /The Vigilant Eating Rule/);
  assert.match(content, /Random Serial Dictatorship and the Core/);
  assert.match(content, /Matching Theory/);
  assert.match(content, /Using an Electromyogram Technique to Detect Muscle Activity/);
  assert.match(content, /Frequency Analysis of the Surface EMG Signal: Best Practices/);
  assert.match(page, /artifact-facts/);
  assert.match(page, /notebook-process/);
  assert.match(page, /experience-skills/);
  assert.match(page, /field-metrics/);
  assert.match(content, /CONTACT CARD BESIDE PRINTER/);
  assert.match(page, /fax-reading/);
});

test("editable copy is organized into valid category files", async () => {
  const { readFile } = await import("node:fs/promises");
  for (const name of ["site","intro","room","computer","references","books","drawer","notebook","board","field-case","fax-contact"]) {
    const source = await readFile(new URL(`../content/${name}.json`, import.meta.url), "utf8");
    assert.doesNotThrow(() => JSON.parse(source), `${name}.json must remain valid JSON`);
  }
  const guide = await readFile(new URL("../content/CONTENT_GUIDE.md", import.meta.url), "utf8");
  assert.match(guide, /Website Copy Editing Guide/);
});

test("3D room and layered object exploration remain connected", async () => {
  const game = await import("node:fs/promises").then(({ readFile }) => readFile(new URL("../app/_components/LabGame.tsx", import.meta.url), "utf8"));
  const closeups = await import("node:fs/promises").then(({ readFile }) => readFile(new URL("../app/_components/ZoneCloseup3D.tsx", import.meta.url), "utf8"));
  const page = await import("node:fs/promises").then(({ readFile }) => readFile(new URL("../app/page.tsx", import.meta.url), "utf8"));
  const drawer = await import("node:fs/promises").then(({ readFile }) => readFile(new URL("../content/drawer.json", import.meta.url), "utf8"));
  const notebook = await import("node:fs/promises").then(({ readFile }) => readFile(new URL("../content/notebook.json", import.meta.url), "utf8"));
  const css = await import("node:fs/promises").then(({ readFile }) => readFile(new URL("../public/site.css", import.meta.url), "utf8"));
  const drawerScene = closeups.match(/function buildDrawer[\s\S]*?function buildPrinterDesk/)?.[0] ?? "";
  const notebookScene = page.match(/function NotebookScene[\s\S]*?const boardNotes/)?.[0] ?? "";
  assert.match(game, /WebGLRenderer/);
  assert.match(game, /cameraPoses/);
  assert.match(game, /Raycaster/);
  assert.match(game, /pointermove/);
  assert.match(game, /onInspect/);
  assert.match(game, /faxReady/);
  assert.match(game, /faxPrinted/);
  assert.match(game, /onPrinterInspect/);
  assert.match(game, /room\.faxAlert\.sceneLabel/);
  assert.doesNotMatch(game, /rover/i);
  assert.match(game, /drawer: \[-3\.53, \.84, -5\.38\]/);
  assert.match(closeups, /WebGLRenderer/);
  assert.match(closeups, /buildBooks/);
  assert.match(closeups, /movie:\$\{movie\.id\}/);
  assert.match(closeups, /hoverOnly=true/);
  assert.match(closeups, /CylinderGeometry\(\.27,\.27,\.018,48\)/);
  assert.match(closeups, /MeshPhysicalMaterial/);
  assert.match(closeups, /RoundedBoxGeometry\(\.72,\.86,\.052/);
  assert.match(closeups, /series:higashino/);
  assert.match(closeups, /hoverOnly=!booksContent\.openingEnabled/);
  assert.match(closeups, /item!=="travelMap"&&!fieldCaseContent\.personalDetailsOpeningEnabled/);
  assert.match(closeups, /siteContent\.shared\.comingSoon/);
  assert.match(closeups, /when those personal close-ups are ready to reopen/);
  assert.doesNotMatch(closeups, /const bookShelf=/);
  assert.doesNotMatch(closeups, /const divider=/);
  assert.match(closeups, /makeBook\(book,index,-\.35\+index\*\.42,\.43,true,false\)/);
  assert.match(closeups, /mediaBasket=true/);
  assert.match(closeups, /group\.add\(hit\)/);
  assert.match(closeups, /filmBasket\.rotation\.y=Math\.PI\/2/);
  assert.match(closeups, /const x=0,y=\.54,z=-\.54\+index\*\.095/);
  assert.doesNotMatch(closeups, /const x=\.34\+index\*\.3/);
  assert.match(closeups, /roundedBox\(8\.25,2\.95,\.22/);
  assert.match(closeups, /books:\{position:\[0,2\.05,9\.4\],target:\[0,1\.62,0\]/);
  assert.match(closeups, /buildDrawer/);
  assert.match(closeups, /monitorScreen/);
  assert.match(closeups, /roundedBox\(3\.45,2\.15,\.28/);
  assert.match(drawer, /ALGORITHM REVISION NOTES/);
  assert.match(drawer, /VERSION 01 → VERSION 02/);
  assert.match(drawer, /random selection among courses with remaining capacity/);
  assert.match(drawer, /balance remaining course capacity with remaining student capacity/);
  assert.match(drawer, /More even describes the project goal/);
  assert.match(drawer, /do not establish a formal fairness guarantee/);
  assert.doesNotMatch(drawer, /No method led every criterion/);
  assert.match(drawer, /walk 68\.75% · bus\/subway 47\.92% · bike 37\.5%/);
  assert.match(drawer, /43 valid entries · 46\.51% said time-consuming · 44\.19% said it helped clearly/);
  assert.match(drawer, /32\.56% unclear guidance\/interface · 32\.56% too many features/);
  assert.match(drawer, /\/archive\/emg-enclosure-interior\.png/);
  assert.match(drawer, /\/archive\/emg-enclosure-exterior\.png/);
  assert.match(page, /className="artifact-media"/);
  assert.match(css, /\.artifact-media \{[^}]*grid-template-columns: repeat\(2,minmax\(0,1fr\)\)/);
  assert.match(css, /\.drawer-document article small \{[^}]*font: clamp\(9px,1\.1vw,11px\)\/1\.55/);
  assert.match(css, /\.drawer-document-return \{[^}]*font: 9px/);
  assert.match(drawerScene, /const cabinetTop=roundedBox\(4\.25,\.18,3\.55/);
  assert.match(drawerScene, /const bottom=roundedBox\(3\.72,\.14,3\.12/);
  assert.match(drawerScene, /const front=roundedBox\(4\.02,1\.18,\.27/);
  assert.match(drawerScene, /tray\.position\.set\(-1,\.05,-\.36\)/);
  assert.match(drawerScene, /monitorAssembly\.scale\.setScalar\(1\.3\)/);
  assert.match(drawerScene, /buildPrinterModel\(workspace,\[2\.75,2\.32,\.35\],\.76,faxPrinted\)/);
  assert.match(drawerScene, /addContactCard\(workspace,\[3\.52,2\.39,1\.15\],-\.12,undefined,\.6\)/);
  assert.equal([...drawerScene.matchAll(/addContactCard\(workspace,/g)].length, 1);
  assert.match(closeups, /buildNotebook/);
  assert.match(closeups, /const table=box\(8,\.35,6\.8,palette\.woodLight/);
  assert.match(closeups, /const matBoard=box\(6\.9,\.06,5\.4,0x213a35/);
  assert.match(closeups, /const researchHit=hitBox\([^\n]+\[left,photo\]\)/);
  assert.doesNotMatch(closeups, /const diagramHit=/);
  assert.match(closeups, /const comparisonSheet=roundedBox/);
  assert.match(closeups, /\[right,comparisonSheet,\.\.\.comparisonBars\]/);
  assert.match(closeups, /const lamp=new THREE\.Group\(\)/);
  assert.match(closeups, /lamp\.position\.set\(2\.7,\.31,-2\.6\)/);
  assert.match(closeups, /lamp\.rotation\.y=-2\.15/);
  assert.match(closeups, /lamp\.scale\.setScalar\(2\)/);
  assert.match(closeups, /lampHead\.add\(shade,reflector,shadeRim,bulb,lampGlow\)/);
  assert.match(closeups, /notebook:\{position:\[-\.35,5\.7,5\.7\],target:\[-\.45,1\.1,0\]/);
  assert.match(notebookScene, /model-detail notebook-detail/);
  assert.doesNotMatch(notebookScene, /setReverse|notebook-turn-control/);
  assert.match(notebook, /CLICK THE LEFT OR RIGHT PAGE TO OPEN A NOTE/);
  assert.match(notebook, /ALGORITHM COMPARISON/);
  assert.match(notebook, /First-Come-First-Serve/);
  assert.match(notebook, /Random Ticket/);
  assert.match(notebook, /Probabilistic \+ Maximum Weight/);
  assert.doesNotMatch(notebook, /dossier/i);
  assert.doesNotMatch(notebook, /"diagram"|ALLOCATION REVISION|Residual probability needed a better rule/);
  assert.doesNotMatch(notebook, /TURN IT OVER|TURN THE PAGE|TURN BACK/);
  assert.match(css, /\.model-detail \.notebook-closeup \{[^}]*aspect-ratio: \.79/);
  assert.match(css, /\.model-detail \.notebook-closeup \{[^}]*width: min\(630px,86vw/);
  assert.match(css, /\.notebook-closeup \.paper-return-control \{[^}]*padding: 6px 8px/);
  assert.match(css, /\.notebook-closeup \{[^}]*background-color: #f1e8c9/);
  assert.doesNotMatch(css, /\.notebook-closeup\.turned|\.notebook-turn-control|\.notebook-pipeline/);
  assert.match(closeups, /buildBoard/);
  assert.match(closeups, /boardContent\.hitLabels\[6\]/);
  assert.match(closeups, /const paper=roundedBox\(note\.w,note\.h,\.045/);
  assert.match(css, /\.evidence-card\.note-card \{[^}]*width: min\(450px,86vw\)/);
  assert.match(css, /\.evidence-card\.note-card blockquote \{[^}]*font-size: clamp\(22px,3vw,32px\)/);
  assert.match(closeups, /buildFieldCase/);
  assert.match(closeups, /buildPrinter/);
  assert.match(closeups, /buildContact/);
  assert.match(closeups, /buildPrinterDesk/);
  assert.match(closeups, /contactCardGroup/);
  assert.match(closeups, /contactCardRaised/);
  assert.match(closeups, /RoundedBoxGeometry/);
  assert.match(closeups, /drawerProgress/);
  assert.match(closeups, /drawerWorkspace/);
  assert.match(closeups, /printProgress/);
  assert.match(closeups, /TubeGeometry/);
  assert.match(closeups, /if\(showFax\)/);
  assert.match(closeups, /onFaxPrinted/);
  assert.match(closeups, /fieldCaseContent\.itemLabels\.target/);
  for (const selector of ["lab-game", "computer-view", "os-screen", "model-scene", "model-detail", "physical-book", "book-turning-sheet", "series-catalog", "contact-reading", "contact-card-detail", "fax-reading", "fax-paper"]) {
    assert.match(css, new RegExp(`\\.${selector}`));
  }
  assert.match(css, /@media \(max-width: 620px\)/);
  assert.match(css, /prefers-reduced-motion/);
  assert.match(css, /contactCardPickup/);
  assert.match(css, /contactCardReturn/);
  assert.match(css, /\.os-window\.is-maximized/);
  assert.match(css, /\.window-controls/);
  assert.match(css, /\.taskbar-app\.active/);
});

test("field case map uses real country geometry instead of hand-drawn continents", async () => {
  const { readFile, readdir } = await import("node:fs/promises");
  const mapSource = await readFile(new URL("../app/_components/fieldCaseMap.ts", import.meta.url), "utf8");
  const photoLibrary = await readFile(new URL("../app/_components/travelPhotoLibrary.ts", import.meta.url), "utf8");
  const page = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  const css = await readFile(new URL("../public/site.css", import.meta.url), "utf8");
  const photoGuide = await readFile(new URL("../app/_assets/travel-map-photos/README.md", import.meta.url), "utf8");
  const nycGuide = await readFile(new URL("../app/_assets/travel-map-photos/new-york-city/ADD-PHOTOS-HERE.md", import.meta.url), "utf8");
  const expectedPhotoCounts = {chongqing:5,kyoto:2,"los-angeles":6,"new-york-city":2,"san-francisco":4,seattle:4,tokyo:2,xian:5};
  for (const [folder,count] of Object.entries(expectedPhotoCounts)) {
    const entries = await readdir(new URL(`../app/_assets/travel-map-photos/${folder}/`, import.meta.url), {withFileTypes:true});
    assert.equal(entries.filter((entry) => entry.isFile() && /\.(?:jpe?g|png|webp|gif|avif)$/i.test(entry.name)).length, count, `${folder} photo count`);
  }
  const countries = JSON.parse(await readFile(new URL("../app/_components/worldCountries110m.json", import.meta.url), "utf8"));
  assert.ok(countries.length >= 170, "the map should retain Natural Earth country coverage");
  assert.ok(countries.every((country) => country.g?.type === "Polygon" || country.g?.type === "MultiPolygon"));
  assert.match(mapSource, /fill\("evenodd"\)/);
  assert.match(mapSource, /\[-width,0,width\]/);
  assert.match(mapSource, /FIELD_CASE_TRAVEL_PINS/);
  assert.match(mapSource, /FIELD_CASE_MAP_VIEWS/);
  assert.match(mapSource, /worldGroup/);
  assert.match(mapSource, /camera\.zoom<2\.25/);
  for (const place of ["Seattle", "San Francisco", "Los Angeles", "San Diego", "New York City", "Philadelphia", "Boston", "Orlando", "Busan", "Bangkok", "Chongqing", "Xi'an", "Shanghai", "Kyoto", "Tokyo", "Beijing", "Macau", "Qingdao", "Dalian", "Beihai", "Lijiang"]) {
    assert.match(mapSource, new RegExp(place.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")));
  }
  assert.doesNotMatch(mapSource, /name:"(?:Nanjing|Suzhou|Yixing)"/);
  assert.equal([...mapSource.matchAll(/\{name:"/g)].length, 21);
  assert.equal([...mapSource.matchAll(/country:"/g)].length, 21);
  assert.equal([...mapSource.matchAll(/photoFolder:"/g)].length, 21);
  assert.equal([...mapSource.matchAll(/region:"asia"/g)].length, 13);
  const worldGroups = [...mapSource.matchAll(/worldGroup:"([^"]+)"/g)].map((match) => match[1]);
  assert.equal(new Set(worldGroups).size, 19);
  assert.match(mapSource, /name:"Seattle"[^\n]+worldGroup:"seattle"/);
  assert.match(mapSource, /name:"Los Angeles"[^\n]+worldGroup:"southern-california"/);
  assert.match(mapSource, /name:"San Diego"[^\n]+worldGroup:"southern-california"/);
  assert.match(mapSource, /name:"Busan"[^\n]+country:"South Korea"[^\n]+worldGroup:"busan"/);
  assert.match(mapSource, /name:"Kyoto"[^\n]+country:"Japan"[^\n]+worldGroup:"kyoto"/);
  assert.doesNotMatch(mapSource, /name:"Osaka"|photoFolder:"osaka"/);
  assert.doesNotMatch(mapSource, /japan-korea|usa-west/);
  const mapReading = page.match(/function FieldMapReading[\s\S]*?\n}\n\nfunction FieldCaseScene/)?.[0] ?? "";
  assert.match(mapReading, /onWheel/);
  assert.match(mapReading, /setPointerCapture/);
  assert.match(mapReading, /field-map-views/);
  assert.match(mapReading, /travelPhotosForPin/);
  assert.match(mapReading, /field-map-memory/);
  assert.match(mapReading, /aria-labelledby="field-map-memory-title"/);
  assert.match(mapReading, /field-map-photo-stage is-/);
  assert.match(mapReading, /photoCloseRef/);
  assert.match(mapReading, /tabIndex=\{0\}/);
  assert.match(mapReading, /preloadTravelPhoto/);
  assert.match(mapReading, /image\.decode\(\)/);
  assert.match(mapReading, /FIELD_CASE_TRAVEL_PINS/);
  assert.match(mapReading, /aria-busy=\{photoStatus==="loading"\}/);
  assert.match(mapReading, /field-map-photo-loading/);
  assert.match(mapReading, /activePhotoSrcRef/);
  assert.match(mapReading, /decodedPhotoSrcRef/);
  assert.match(mapReading, /photoImageCacheRef/);
  assert.match(mapReading, /photoImageCacheRef\.current\.set\(photo\.src,image\)/);
  assert.match(mapReading, /decodedPhotoSrcRef\.current\.add\(photo\.src\)/);
  assert.match(mapReading, /decodedPhotoSrcRef\.current\.add\(expectedSrc\)/);
  assert.match(mapReading, /decodedPhotoSrcRef\.current\.has\(nextPhoto\.src\)/);
  assert.match(mapReading, /decodedPhotoSrcRef\.current\.delete\(currentPhoto\.src\)/);
  assert.match(mapReading, /navigationLockedRef/);
  assert.match(mapReading, /await image\.decode\(\)/);
  assert.doesNotMatch(mapReading, /void image\.decode\(\)/);
  assert.match(mapReading, /Promise\.all\(warmups\)/);
  assert.match(mapReading, /photoImageCacheRef\.current\.forEach/);
  assert.match(mapReading, /photoImageCacheRef\.current\.clear\(\)/);
  assert.match(mapReading, /decodedPhotoSrcRef\.current\.clear\(\)/);
  assert.match(mapReading, /image\.onload=null/);
  assert.match(mapReading, /image\.onerror=null/);
  assert.doesNotMatch(mapReading, /TravelPhotoLayout|photoLayout|layoutForAspect/);
  assert.doesNotMatch(mapReading, /--photo-aspect|--photo-frame-width/);
  assert.match(mapReading, /Previous photo/);
  assert.match(mapReading, /Next photo/);
  assert.match(mapReading, /randomLostTravelMessage/);
  assert.match(photoLibrary, /import\.meta\.glob/);
  assert.match(photoLibrary, /photoFolder/);
  assert.match(photoLibrary, /localeCompare/);
  assert.doesNotMatch(page, /manifest\.json/);
  assert.match(css, /\.field-map-memory/);
  assert.match(css, /\.field-map-memory \{[^}]*720px[^}]*115\.2svh - 281px/);
  assert.match(css, /\.field-map-memory \{[^}]*aspect-ratio: 720 \/ 625/);
  assert.match(css, /\.field-map-memory \{[^}]*grid-template: auto minmax\(0,1fr\) auto \/ minmax\(0,1fr\)/);
  assert.match(css, /\.field-map-memory \{[^}]*background-color: #ded2ad/);
  assert.match(css, /animation: fieldMapMemoryIn/);
  assert.match(css, /\.field-map-memory > header, \.field-map-photo-stage, \.field-map-memory > footer \{[^}]*min-width: 0[^}]*max-width: 100%/);
  assert.match(css, /\.field-map-memory > header \{[^}]*min-height: 54px[^}]*padding: 7px 2px 6px 5px[^}]*border-bottom:/);
  assert.match(css, /\.field-map-memory > header > div \{[^}]*transform: translateY\(2px\)/);
  assert.match(css, /\.field-map-memory > header h2 \{[^}]*padding-bottom: 5px[^}]*font: 24px\/1 "Segoe Print",cursive/);
  assert.match(css, /\.field-map-photo-stage \{[^}]*display: flex/);
  assert.match(css, /\.field-map-photo-stage \{[^}]*width: auto[^}]*height: auto/);
  assert.match(css, /\.field-map-photo-stage \{[^}]*padding: 0/);
  assert.doesNotMatch(css, /\.field-map-photo-stage \{[^}]*(?:aspect-ratio|grid-template-columns):/);
  assert.match(css, /\.field-map-photo-stage > img \{[^}]*object-fit: contain/);
  assert.match(css, /\.field-map-photo-stage > img \{[^}]*width: 100%[^}]*height: 100%/);
  assert.match(css, /\.field-map-photo-stage > img \{[^}]*min-width: 0[^}]*max-width: 100%[^}]*max-height: 100%/);
  assert.doesNotMatch(css, /\.field-map-photo-stage > img \{[^}]*max-width: none/);
  assert.match(css, /\.field-map-photo-stage\.is-loading > img \{[^}]*filter: blur/);
  assert.match(css, /\.field-map-photo-stage\.is-loading > img \{[^}]*opacity: 1/);
  assert.doesNotMatch(css, /\.field-map-photo-stage\.is-loading > img \{[^}]*transform:/);
  assert.match(css, /\.field-map-photo-loading, \.field-map-photo-message \{[^}]*position: absolute/);
  assert.match(css, /\.field-map-photo-stage \{[^}]*border: 0/);
  assert.match(css, /\.field-map-photo-stage \{[^}]*background: transparent/);
  assert.match(css, /\.field-map-photo-stage \{[^}]*box-shadow: none/);
  assert.match(css, /\.field-map-photo-loading \{[^}]*background: transparent/);
  assert.match(css, /\.field-map-photo-message\.lost \{[^}]*background: transparent/);
  assert.match(css, /\.field-map-photo-loading i \{[^}]*rgba\(79,70,48,.28\)/);
  assert.doesNotMatch(css, /\.field-map-photo-stage \{[^}]*background: #293732/);
  assert.doesNotMatch(css, /\.field-map-photo-message\.lost \{[^}]*background: #f2ead3/);
  assert.doesNotMatch(css, /\.field-map-photo-loading i \{[^}]*rgba\(246,237,211,.4\)/);
  assert.doesNotMatch(css, /\.field-map-photo-stage \{[^}]*inset 0 0 0 5px/);
  assert.doesNotMatch(css, /\.field-map-photo-stage \{[^}]*3px 5px/);
  assert.match(css, /padding: 15px 15px 12px/);
  assert.match(css, /padding: 12px 12px 10px/);
  assert.match(css, /@media \(max-width: 620px\)[\s\S]*\.field-map-memory \{[^}]*714px[^}]*100svh - 104px[^}]*100vw \+ 90px/);
  assert.match(css, /@media \(max-width: 620px\)[\s\S]*\.field-map-photo-stage \{[^}]*padding: 0/);
  assert.match(css, /@media \(max-height: 500px\) and \(min-width: 621px\)[\s\S]*\.field-map-memory \{[^}]*115\.2svh - 184px[^}]*max-height: calc\(100% - 32px\)/);
  assert.doesNotMatch(css, /--photo-aspect|--photo-frame-width/);
  assert.doesNotMatch(css, /\.field-map-photo-stage\.is-(?:loading|ready|lost)[^{]*\{[^}]*(?:width|height|padding|margin|aspect-ratio):/);
  assert.doesNotMatch(css, /\.field-map-memory\.is-photo-ready/);
  assert.doesNotMatch(css, /field-map-photo-stage:not\(\.is-ready\)/);
  assert.match(photoGuide, /不需要修改代码/);
  assert.match(nycGuide, /new-york-city/);
  assert.doesNotMatch(mapReading, /item\.copy|field-map-places|object-tags/);
  assert.doesNotMatch(mapSource, /landMasses/);
});
