import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { readFile } from "node:fs/promises";
import test from "node:test";

async function render() {
  const workerUrl = new URL("../dist/server/index.js", import.meta.url);
  workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}`);
  const { default: worker } = await import(workerUrl.href);
  return worker.fetch(
    new Request("http://localhost/", { headers: { accept: "text/html", host: "localhost" } }),
    { ASSETS: { fetch: async () => new Response("Not found", { status: 404 }) } },
    { waitUntil() {}, passThroughOnException() {} },
  );
}

test("server renders a personal laboratory before revealing the mystery", async () => {
  const response = await render();
  assert.equal(response.status, 200);
  const html = await response.text();
  assert.match(html, /Lab 17 Interactive Portfolio/i);
  assert.match(html, /Come in.*lab is.*still awake/is);
  assert.match(html, /ENTER LAB 17/);
  assert.match(html, /Wenrui.*Alina.*Wu/i);
  assert.match(html, /This is where Alina Wu keeps algorithms, physical prototypes, research notes, and questions about how systems become understandable and useful to people/);
  assert.doesNotMatch(html, /missing person/i);
  assert.doesNotMatch(html, /[\u4e00-\u9fff]/);
});

test("website version displays and release tag match package version", async () => {
  const packageJson = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  const response = await render();
  const html = await response.text();
  const page = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  const version = packageJson.version;

  assert.ok(html.includes(`v${version}`), "rendered website must include the package version");
  assert.ok((page.match(/siteContent\.brand\.version/g) ?? []).length >= 2, "both website version displays must use the shared package-backed version");

  let tag;
  try {
    tag = execFileSync("git", ["describe", "--tags", "--exact-match", "HEAD"], { encoding: "utf8" }).trim();
  } catch {
    tag = "";
  }
  if (tag) assert.equal(tag, `v${version}`, "release tag must match package version");
});

test("source contains six room objects, real work, and a progressive reveal", async () => {
  const { readFile } = await import("node:fs/promises");
  const page = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  const contentFiles = ["site","intro","room","computer","references","books","drawer","notebook","board","field-case","fax-contact"];
  const content = (await Promise.all(contentFiles.map((name) => readFile(new URL(`../content/${name}.json`, import.meta.url), "utf8")))).join("\n");
  for (const zone of ["computer", "drawer", "notebook", "books", "board", "fieldcase"]) {
    assert.match(page, new RegExp(`active===\\"${zone}\\"|active!==\\"${zone}\\"|\\"${zone}\\"`));
  }
  assert.match(page, /from "@\/content"/);
  assert.match(content, /ALINA\.OS/);
  assert.match(content, /PROJECTS \/ 3 ITEMS/);
  assert.match(content, /README\.txt/);
  assert.match(content, /LAB_LOG\.md/);
  assert.match(content, /Joining Thermo Fisher Scientific/);
  assert.doesNotMatch(content, /ABOUT\.txt/);
  assert.doesNotMatch(content, /[‘’]/);
  assert.match(page, /lab-log-line/);
  assert.match(content, /USER PROFILE \/ ALINA\.WU/);
  assert.match(page, /os-profile-trigger/);
  assert.match(page, /onToggleMaximize=\{toggleMaximizedWindow\}/);
  assert.match(page, /maximizedWindow===\"references\"/);
  assert.match(page, /window-maximize/);
  assert.match(page, /window-close/);
  assert.match(page, /taskbar-apps/);
  assert.match(page, /taskbarWindows\.map\(\(windowId\)=>/);
  assert.match(page, /taskbarWindowIds\.filter\(showComputerWindow\)/);
  assert.match(page, /label:"REFERENCES"/);
  assert.match(page, /label:"ALLOCATION"/);
  assert.match(page, /computerContent\.sidebar\.references\}<\/button><button onClick=\{\(\) => openComputerFile\(\"lablog\"\)\}/);
  assert.doesNotMatch(page, /computerContent\.sidebar\.readme/);
  assert.match(content, /Quality of Life in Shanghai/);
  assert.match(content, /Automatic and Satisfactory Course Assignment/);
  assert.match(content, /Monitoring Device for Muscle Usage.*Behavior/);
  assert.match(content, /Social Futures Lab/i);
  assert.match(content, /Thermo Fisher Scientific/i);
  assert.match(content, /User has not checked in/i);
  assert.match(content, /Alina Wu has been offline for four days.*This workstation continues to sync/i);
  assert.doesNotMatch(content, /Her computer/);
  assert.doesNotMatch(content, /Why is this appearing on a portfolio computer/);
  assert.doesNotMatch(content, /I am not missing/);
  assert.match(content, /The first wellbeing prototype is ready for feedback/);
  assert.match(content, /FEEDBACK IN PROGRESS/);
  assert.match(content, /awu78@uw\.edu/);
  assert.doesNotMatch(content, /hello@example\.com/);
  assert.match(content, /INCOMING FAX/);
  assert.match(content, /CLICK THE HIGHLIGHTED PRINTER/);
  assert.match(page, /onDoubleClick/);
  assert.doesNotMatch(page, /DOUBLE CLICK TO OPEN/);
  assert.doesNotMatch(page, />DOUBLE CLICK</);
  for (const zone of ["drawer", "books", "notebook", "board", "fieldcase", "printer", "contact"]) {
    assert.match(page, new RegExp(`ZoneCloseup3D zone=\\"${zone}\\"`));
  }
  assert.doesNotMatch(content, /TURN PAGE/);
  assert.doesNotMatch(page, /book-turning-sheet/);
  assert.match(content, /FIELD CASE \/ LIFE OUTSIDE THE LAB/);
  assert.match(content, /WORLD MAP \/ PLACES VISITED/);
  assert.match(content, /RECIPE CARDS \/ COOKING \+ BAKING/);
  assert.match(content, /LASER SHOOTING \/ HIGH SCHOOL TEAM/);
  assert.match(page, /field-map-reading/);
  assert.match(page, /drawFieldCaseMapViewport/);
  assert.doesNotMatch(content, /editable layout markers|Replace prompts and layout pins/);
  assert.match(content, /REFERENCES\.web/);
  assert.match(content, /PERSONAL SHELF \/ BOOKS \+ FILMS/);
  assert.match(content, /LAB 17 \/ PINNED TODO/);
  assert.match(content, /turn the EMG model into an explorable exhibit/);
  assert.match(content, /add a guide who knows the room/);
  assert.match(content, /open richer project evidence/);
  assert.match(content, /show what has been discovered/);
  assert.match(content, /add a visual Version History/);
  assert.match(content, /make every object feel more physical/);
  assert.match(content, /design touch controls for the room/);
  assert.match(content, /BOARD \/ PINNED TODO/);
  assert.doesNotMatch(content, /NOTE BOARD \/ FOLLOW THE THREADS/);
  assert.doesNotMatch(content, /check potential confounders/);
  assert.doesNotMatch(content, /evaluate the whole distribution/);
  assert.doesNotMatch(content, /test the intervention/);
  assert.doesNotMatch(content, /make the workflow legible before changing it/);
  assert.doesNotMatch(content, /BOARD \/ PRINCIPLES/);
  assert.match(content, /"openingEnabled": false/);
  assert.match(content, /"personalDetailsOpeningEnabled": false/);
  assert.match(content, /"comingSoon": "COMING SOON"/);
  assert.match(content, /Whole Brain Living/);
  assert.match(content, /To Live/);
  assert.match(content, /Cries in the Drizzle/);
  assert.match(content, /Keigo Higashino/);
  assert.match(content, /Journey Under the Midnight Sun/);
  assert.match(content, /Farewell My Concubine/);
  assert.doesNotMatch(page, /series:higashino/);
  assert.doesNotMatch(page, /if\(!booksContent\.openingEnabled\)return/);
  assert.doesNotMatch(page, /selectedMovie|dvd-case-detail|dvd-zoom/);
  assert.match(content, /A New Solution to the Random Assignment Problem/);
  assert.match(content, /Simultaneously Achieving Ex-Ante and Ex-Post Fairness/);
  assert.match(content, /The Vigilant Eating Rule/);
  assert.match(content, /Random Serial Dictatorship and the Core/);
  assert.match(content, /Matching Theory/);
  assert.match(content, /Using an Electromyogram Technique to Detect Muscle Activity/);
  assert.match(content, /Frequency Analysis of the Surface EMG Signal: Best Practices/);
  assert.match(page, /artifact-facts/);
  assert.match(page, /notebook-process/);
  assert.match(page, /experience-skills/);
  assert.match(page, /field-metrics/);
  assert.match(content, /CONTACT CARD BESIDE PRINTER/);
  assert.match(page, /fax-reading/);
});

test("portrait room, computer, and closeup sizing stay isolated from desktop architecture", async () => {
  const [layout, page, game, closeups, framing, portraitComputer, siteCss, portraitCss] = await Promise.all([
    readFile(new URL("../app/layout.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/page.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/_components/LabGame.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/_components/ZoneCloseup3D.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/_components/cameraFraming.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/_components/PortraitComputerView.tsx", import.meta.url), "utf8"),
    readFile(new URL("../public/site.css", import.meta.url), "utf8"),
    readFile(new URL("../public/portrait.css", import.meta.url), "utf8"),
  ]);

  assert.ok(layout.indexOf('import "../public/site.css"') < layout.indexOf('import "../public/portrait.css"'), "portrait overrides must load after the shared stylesheet");
  assert.match(layout, /viewportFit: "cover"/);
  assert.match(portraitCss.trim(), /^@media \(orientation: portrait\) \{/);
  assert.equal((portraitCss.match(/@media \(orientation: portrait\)/g) ?? []).length, 1, "portrait styling must have one explicit isolation boundary");
  assert.equal((page.match(/<LabGame\b/g) ?? []).length, 1, "the room must keep one LabGame instance");
  assert.equal((game.match(/<canvas\b/g) ?? []).length, 1, "LabGame must keep one WebGL canvas");
  assert.match(game, /if\(rect\.width<2\|\|rect\.height<2\)return/);
  assert.match(game, /const nextAspect=rect\.width\/rect\.height/);
  assert.match(game, /isPortrait=rect\.height>=rect\.width/);
  assert.match(game, /renderer\.setSize\(rect\.width,rect\.height,false\)/);
  assert.match(game, /camera\.aspect=nextAspect/);
  assert.match(game, /camera\.fov=43/);
  assert.match(game, /portraitDistanceScale=isPortrait\?Math\.min\(aspectOverflowDistanceScale\(nextAspect\),MAX_PORTRAIT_ROOM_DISTANCE_SCALE\):1/);
  assert.match(game, /renderer\.toneMappingExposure=isPortrait\?PORTRAIT_ROOM_EXPOSURE:DEFAULT_ROOM_EXPOSURE/);
  assert.match(game, /desiredPosition\.clone\(\)\.sub\(desiredTarget\)\.multiplyScalar\(portraitDistanceScale\)/);
  assert.match(game, /const portraitPan=roomPanOffsets\[roomPanViewRef\.current\]\+portraitDragOffset/);
  assert.match(game, /roomPanViewChangeRef\.current\(roomPanOrder\[nextIndex\]\)/, "portrait room swipes must snap between complete lateral views");
  assert.match(game, /booksZoneIndicator\.position\.z=zonePositions\.books\[2\]\+\(isPortrait\?PORTRAIT_BOOKS_ZONE_FRONT_OFFSET:0\)/, "portrait room must bring the bookshelf indicator in front of the shelf");
  assert.doesNotMatch(game, /booksZoneRing\.rotation\.x=/, "portrait bookshelf indicator must retain its original orientation");
  assert.match(game, /booksZoneHit\.scale\.setScalar\(isPortrait\?PORTRAIT_BOOKS_ZONE_HIT_SCALE:1\)/, "portrait bookshelf must have a larger touch target");
  assert.match(game, /ring\.userData\.interactionOverlay = true/);
  assert.match(game, /hit\.userData\.interactionOverlay = true/);
  assert.match(game, /object\.castShadow=!isInteractionOverlay/, "room interaction overlays must never cast geometry-shaped shadows");
  assert.doesNotMatch(game, /portraitPosition|portraitTarget|camera\.fov\s*=\s*isPortrait\s*\?/);
  assert.match(game, /new ResizeObserver\(resize\)/);
  assert.match(framing, /IDEAL_LANDSCAPE_ASPECT/);
  assert.match(framing, /Math\.max\(1, IDEAL_LANDSCAPE_ASPECT \/ safeAspect\)/);
  assert.match(page, /<div className="computer-view computer-view-desktop"/);
  assert.match(page, /<PortraitComputerView computerWindows=\{computerWindows\} referenceFilter=\{referenceFilter\} bulletin=\{bulletin\}/);
  assert.match(page, /onOpenFile=\{openComputerFile\}[\s\S]*onOpenRoot=\{openPortraitComputerRoot\}[\s\S]*onFocusWindow=\{focusComputerWindow\}[\s\S]*onBack=\{backPortraitComputer\}[\s\S]*onOpenReferences=\{openReferences\}/);
  assert.match(page, /setComputerWindows\(file==="desktop"\?\[\]:\[file\]\)/, "portrait apps must replace desktop window stacking with top-level phone destinations");
  assert.doesNotMatch(page, /computerViewRef|computerOsRef|--computer-scale|--computer-layout-(?:width|height)|scrollWidth/);
  assert.doesNotMatch(page, /className="computer-os"/);
  assert.match(siteCss, /\.portrait-computer-view \{ display: none; \}/);
  assert.match(portraitCss, /\.computer-view-desktop \{\s*display: none/);
  assert.match(portraitCss, /\.portrait-computer-view \{[\s\S]*display: grid;[\s\S]*height: 100svh;[\s\S]*height: 100dvh;[\s\S]*overflow: hidden/);
  assert.doesNotMatch(`${portraitComputer}\n${portraitCss}`, /--computer-(?:scale|layout)|transform:\s*scale\(|\bzoom\s*:/, "portrait Computer must not return to whole-interface scaling");
  assert.doesNotMatch(page, /PortraitRoom|MobileRoom|navigator\.userAgent|matchMedia\([^\n]+orientation/);
  assert.match(page, /zoneOrder\.map\(\(zone\) => <button[^>]+onClick=\{\(\) => inspect\(zone\)\}/);
  assert.match(page, /showRoomPanHint&&<div className="room-pan-hint"[\s\S]*portraitPanHint/, "portrait room must explain the horizontal swipe gesture without permanent view controls");
  assert.match(page, /setRoomPanView\(view\);\s*setShowRoomPanHint\(false\)/, "the swipe hint must dismiss after the visitor changes the room view");
  assert.doesNotMatch(page, /room-pan-nav|Show \$\{view\} side of the room/);
  assert.match(siteCss, /\.room-pan-hint \{ display: none; \}/, "room pan hint must remain hidden from desktop layouts");
  assert.match(portraitCss, /\.room-entered \.room-pan-hint \{[\s\S]*display: flex;[\s\S]*animation: roomPanHintIn/);
  assert.match(page, /PORTRAIT_MAP_INITIAL_ZOOM[\s\S]*portraitMapInitializedRef[\s\S]*sheet\.clientHeight>=sheet\.clientWidth[\s\S]*camera\.zoom<PORTRAIT_MAP_INITIAL_ZOOM/, "portrait travel map must open closer without changing its desktop camera");
  assert.match(page, /setShowMapPanHint\(false\)[\s\S]*className="field-map-pan-hint"[\s\S]*fieldCaseContent\.mapPortraitPanHint/, "portrait travel map must explain horizontal dragging until the visitor uses it");
  assert.match(siteCss, /\.field-map-pan-hint \{ display: none; \}/, "map pan hint must stay hidden from desktop layouts");
  assert.match(portraitCss, /\.room-shell \.field-detail \{[\s\S]*padding: 14px/, "portrait map closeup must leave space around every edge");
  assert.match(portraitCss, /\.room-shell \.field-map-reading \{[\s\S]*width: min\(100%,calc\(\(100dvh - 128px\)\*\.7\)\);[\s\S]*height: auto;[\s\S]*aspect-ratio:[\s\S]*border: 1px solid #8a7453/, "portrait map must remain a proportioned framed sheet inside its inset closeup");
  assert.doesNotMatch(portraitCss, /\.room-shell \.field-map-reading \{[^}]*border-radius/, "the map paper must retain square corners");
  assert.match(portraitCss, /\.room-shell \.field-map-pan-hint \{[\s\S]*display: flex;[\s\S]*animation: roomPanHintIn/);
  for (const zone of ["computer", "drawer", "notebook", "books", "board", "fieldcase"]) {
    assert.match(page, new RegExp(`active===\\"${zone}\\"`), `${zone} must retain its existing closeup branch`);
  }

  for (const zone of ["books", "drawer", "notebook", "board", "fieldcase", "printer", "contact"]) {
    assert.match(page, new RegExp(`className=\"tactile-scene\"[\\s\\S]{0,900}<ZoneCloseup3D zone=\"${zone}\"`), `${zone} must render inside the sized tactile closeup container`);
  }

  assert.match(closeups, /closeupFog\.density=DEFAULT_CLOSEUP_FOG_DENSITY\/portraitDistanceScale/, "portrait closeups must compensate fog when the camera moves back to fit their width");
  assert.match(closeups, /renderer\.toneMappingExposure=isPortrait\?PORTRAIT_CLOSEUP_EXPOSURE:DEFAULT_CLOSEUP_EXPOSURE/, "portrait closeups must retain readable exposure without changing desktop rendering");

  const declarationsFor = (selector) => {
    const start = portraitCss.indexOf(`${selector} {`);
    assert.notEqual(start, -1, `${selector} must have an explicit portrait sizing contract`);
    return portraitCss.slice(start, portraitCss.indexOf("}", start));
  };
  const layerContract = declarationsFor(".room-shell > .modal-layer.tactile-layer");
  const sceneContract = declarationsFor(".room-shell > .modal-layer.tactile-layer > .tactile-scene");
  const stageContract = declarationsFor(".room-shell > .modal-layer.tactile-layer > .tactile-scene > .model-scene");
  const canvasContract = declarationsFor(".room-shell > .modal-layer.tactile-layer > .tactile-scene > .model-scene > canvas");
  assert.match(layerContract, /display: grid[\s\S]*grid-template-columns: minmax\(0,1fr\)[\s\S]*grid-template-rows: minmax\(0,1fr\)[\s\S]*place-items: stretch/);
  assert.match(layerContract, /height: 100svh[\s\S]*height: 100dvh[\s\S]*min-height: 0/);
  assert.match(sceneContract, /place-self: stretch[\s\S]*width: auto[\s\S]*height: auto[\s\S]*min-width: 0[\s\S]*min-height: 0[\s\S]*max-height: none/);
  assert.match(stageContract, /inset: 58px 0 0[\s\S]*height: auto[\s\S]*min-height: 1px/);
  assert.match(canvasContract, /display: block[\s\S]*width: 100%[\s\S]*height: 100%[\s\S]*min-height: 1px/);
  const phoneStageContract = declarationsFor(".portrait-phone-stage");
  const phoneHomeContract = declarationsFor(".portrait-phone-home");
  const phoneAppContract = declarationsFor(".portrait-phone-app");
  const appContentContract = declarationsFor(".portrait-phone-app-content");
  const bulletinContract = declarationsFor(".portrait-phone-notification");
  const bulletinMetaContract = declarationsFor(".portrait-notification-content small");
  const referenceHeaderMetaContract = declarationsFor(".portrait-references > header small");
  const referenceArticleMetaContract = declarationsFor(".portrait-references article > small");
  const notebookScrollContract = declarationsFor(".room-shell .notebook-scroll");
  const notebookPaperContract = declarationsFor(".room-shell .model-detail .notebook-closeup");
  const notebookMarginContract = declarationsFor(".room-shell .model-detail .notebook-closeup::before");
  const notebookReturnContract = declarationsFor(".room-shell .notebook-closeup .paper-return-control");
  const drawerPaperContract = declarationsFor(".room-shell .drawer-document-paper");
  const drawerReturnContract = declarationsFor(".room-shell .drawer-document-return");
  const drawerReturnHitContract = declarationsFor(".room-shell .drawer-document-return::before");
  const drawerArticleContract = declarationsFor(".room-shell .drawer-document article");
  const boardCardContract = declarationsFor(".room-shell .evidence-card.note-card");
  assert.match(phoneStageContract, /grid-row: 2[\s\S]*min-height: 0[\s\S]*overflow: hidden/);
  assert.match(phoneHomeContract, /display: grid[\s\S]*height: 100%[\s\S]*min-height: 0/);
  assert.match(phoneAppContract, /display: grid[\s\S]*grid-template-rows: auto minmax\(0,1fr\)[\s\S]*height: 100%/);
  assert.match(appContentContract, /min-height: 0[\s\S]*overflow-x: hidden[\s\S]*overflow-y: auto[\s\S]*overscroll-behavior: contain/);
  assert.match(bulletinContract, /position: absolute[\s\S]*z-index: 20[\s\S]*border: 1px solid var\(--red\)[\s\S]*touch-action: pan-x/, "portrait notification must float above phone content and own its vertical swipe gesture");
  assert.match(bulletinMetaContract, /color: var\(--red\)/, "portrait notification metadata must retain the desktop warning color");
  assert.match(referenceHeaderMetaContract, /color: var\(--cyan\)/, "reference header metadata must retain its dark-surface contrast");
  assert.match(referenceArticleMetaContract, /color: #a44235/, "reference card metadata must retain its light-paper contrast");
  assert.match(notebookScrollContract, /overflow-y: auto[\s\S]*overscroll-behavior: contain[\s\S]*touch-action: pan-y[\s\S]*padding-bottom:/, "portrait notebook paper must scroll without hiding its final lines beneath the return control");
  assert.match(notebookPaperContract, /--portrait-notebook-rule: clamp\([\s\S]*width: min\(88vw,\d+px,calc\(\(100dvh - 96px\)\*\.79\)\)[\s\S]*max-width: none[\s\S]*aspect-ratio: \.79[\s\S]*background-repeat: repeat-y,no-repeat[\s\S]*background-size:[\s\S]*var\(--portrait-notebook-rule\)/, "portrait notebook papers must keep their established ratio at a responsive tablet cap while their rules scale continuously from the top edge");
  assert.match(notebookMarginContract, /position: absolute[\s\S]*top: 0[\s\S]*bottom: 0[\s\S]*left: 10%[\s\S]*width: 1px/, "portrait notebook paper must render one uninterrupted margin line from top to bottom");
  assert.match(portraitCss, /\.room-shell \.notebook-closeup p,\s*\.room-shell \.notebook-process li,\s*\.room-shell \.notebook-closeup blockquote \{[^}]*font-size: clamp\([^}]*line-height: var\(--portrait-notebook-rule\)/, "portrait notebook copy must scale with its ruled paper");
  assert.match(notebookReturnContract, /min-height: 0[\s\S]*padding:[\s\S]*font-size:/, "phone-sized portrait notebooks must retain a compact visible return control");
  assert.match(portraitCss, /@media \(min-width: 621px\) \{[\s\S]*\.room-shell \.notebook-closeup \.paper-return-control \{[\s\S]*min-height: clamp\([\s\S]*padding: clamp\([\s\S]*font-size: clamp\(/, "tablet-sized portrait notebooks must enlarge the return control independently from phones");
  assert.match(portraitCss, /@media \(min-width: 520px\) and \(min-height: 700px\) \{[\s\S]*\.room-shell \.notebook-scroll \{[\s\S]*overflow-y: hidden[\s\S]*touch-action: manipulation/, "roomy portrait notebooks, including a 540 by 720 viewport, must show their full page without an unnecessary inner scroller");
  assert.match(drawerPaperContract, /width: min\(88vw,\d+px,calc\(\(100dvh - 112px\)\*\.78\)\)[\s\S]*aspect-ratio: \.78[\s\S]*max-width: none/, "portrait drawer documents must keep their paper ratio while respecting a tablet-sized cap");
  assert.match(drawerReturnContract, /top:[\s\S]*right:[\s\S]*padding:[\s\S]*font-size:/, "phone-sized portrait drawer documents must use a compact visible return control");
  assert.match(drawerReturnHitContract, /position: absolute[\s\S]*inset: -10px/, "the compact drawer return control must retain an expanded touch target");
  assert.match(portraitCss, /@media \(min-width: 621px\) \{[\s\S]*\.room-shell \.drawer-document-return \{[\s\S]*font-size: 9px/, "tablet-sized portrait drawer documents must preserve their larger return control");
  assert.match(drawerArticleContract, /height: 100%[\s\S]*min-height: 0[\s\S]*max-height: none[\s\S]*overflow-y: auto[\s\S]*touch-action: pan-y/, "long drawer content must scroll inside the proportioned paper");
  assert.match(boardCardContract, /width: min\(86vw,560px,calc\(\(100dvh - 126px\)\*1\.35\)\)[\s\S]*min-height: 330px[\s\S]*max-width: none[\s\S]*overflow-y: auto[\s\S]*aspect-ratio: auto/, "portrait board cards must respond to the viewport while staying compact enough for their short content");
  assert.match(portraitCss, /\.portrait-home-apps \{[\s\S]*grid-template-columns: repeat\(3,minmax\(0,1fr\)\)/);
  assert.match(portraitCss, /\.portrait-app-icon \{[\s\S]*border-radius: 22%/);
  assert.match(portraitCss, /\.portrait-phone-dock \{[\s\S]*backdrop-filter: blur\(20px\)/);
  assert.match(portraitCss, /\.portrait-phone-systembar button \{[\s\S]*height: 44px/);
  assert.match(portraitComputer, /from "@\/content"/);
  assert.match(portraitComputer, /const activeWindow=computerWindows\.at\(-1\)\?\?null/);
  assert.match(portraitComputer, /const canGoBack=[\s\S]*computerWindows\.length>1/);
  assert.match(portraitComputer, /className="portrait-phone-statusbar"[\s\S]*className="portrait-room-return"[\s\S]*onClick=\{onLeave\}/);
  assert.match(portraitComputer, /className="portrait-home-apps"[\s\S]*PhoneAppIcon kind="profile"[\s\S]*PhoneAppIcon kind="notes"[\s\S]*PhoneAppIcon kind="experience"/);
  assert.match(portraitComputer, /className="portrait-phone-dock"[\s\S]*PhoneAppIcon kind="projects"[\s\S]*PhoneAppIcon kind="references"[\s\S]*PhoneAppIcon kind="lablog"/);
  assert.match(portraitComputer, /className="portrait-phone-navbar"[\s\S]*onClick=\{canGoBack\?onBack:\(\)=>onOpenRoot\("desktop"\)\}/);
  assert.match(portraitComputer, /className="portrait-phone-systembar"[\s\S]*aria-label="Go to Home Screen"/);
  assert.match(portraitComputer, /notesOpen=activeWindow==="readme"[\s\S]*is-notes-active/);
  assert.match(portraitComputer, /className="portrait-document portrait-apple-note"[\s\S]*computerContent\.readme\.mobileMeta[\s\S]*computerContent\.readme\.mobileTitle[\s\S]*className="portrait-notes-toolbar"/, "portrait Notes must use a dedicated phone-native note surface");
  assert.match(portraitComputer, /className=\{notesOpen\?"portrait-notes-access":""\}[\s\S]*computerContent\.readme\.mobileAccess/, "portrait Notes must identify the shared note as view only");
  assert.match(portraitComputer, /className="portrait-notes-readonly"[\s\S]*NotesToolIcon kind="lock"[\s\S]*computerContent\.readme\.mobileReadOnly/);
  assert.match(portraitComputer, /className="portrait-notes-tools"[\s\S]*notesTools\.map[\s\S]*disabled[\s\S]*NotesToolIcon kind=\{tool\.kind\}/, "unavailable note tools must be honest disabled controls");
  assert.match(portraitComputer, /viewBox="0 0 24 24"/, "note toolbar artwork must share one centered SVG coordinate system");
  assert.doesNotMatch(portraitComputer, /portrait-notes-nav-actions|portrait-notes-toolbar" aria-hidden/, "note controls must not masquerade as decorative actions");
  assert.match(portraitCss, /\.portrait-apple-note \{[\s\S]*display: grid;[\s\S]*background: #fbfaf6/);
  assert.match(portraitCss, /\.portrait-notes-toolbar \{[\s\S]*position: sticky;[\s\S]*bottom: 0/);
  assert.match(portraitCss, /\.portrait-notes-tools button \{[\s\S]*display: grid;[\s\S]*place-items: center/);
  assert.match(portraitCss, /\.portrait-notes-tools svg \{[\s\S]*width: 24px;[\s\S]*height: 24px/);
  assert.match(page, /computerContent\.readme\.meta[\s\S]*computerContent\.readme\.title/, "desktop README must keep its existing content fields");
  assert.match(portraitComputer, /useState<LabLogFilter>\("all"\)/);
  assert.match(portraitComputer, /visibleLabLogEntries=[\s\S]*entry\.type\.toLowerCase\(\)\.includes\(labLogFilter\)/);
  assert.match(portraitComputer, /className="portrait-log-filters"[\s\S]*aria-pressed=\{labLogFilter===filter\.id\}/);
  assert.match(portraitComputer, /className="portrait-log-timeline"[\s\S]*visibleLabLogEntries\.map/);
  assert.match(portraitCss, /\.portrait-log-filters \{[\s\S]*grid-template-columns: repeat\(3,minmax\(0,1fr\)\)/);
  assert.match(portraitCss, /\.portrait-log-timeline \{[\s\S]*position: relative[\s\S]*padding-left/);
  assert.match(portraitCss, /\.portrait-log-timeline p \{[\s\S]*grid-template-columns: auto minmax\(0,1fr\)/);
  assert.doesNotMatch(portraitComputer, /portrait-mobile-appbar|portrait-mobile-tabs|const tabs:/, "portrait computer must use phone home and app navigation instead of a desktop-like global tab bar");
  assert.doesNotMatch(portraitComputer, /portrait-computer-panel|portrait-panel-bar|portrait-bulletin/, "portrait computer must not retain desktop window or popup chrome");
  for (const windowId of ["profile","readme","lablog","projects","map","allocation","emg","experience","research","internship","references"]) {
    assert.match(portraitComputer, new RegExp(`(?:activeWindow===\\"${windowId}\\"|\\[\\"map\\",\\"allocation\\",\\"emg\\"\\]|\\[\\"research\\",\\"internship\\"\\])`), `${windowId} must remain reachable in the portrait computer`);
  }
  assert.match(portraitComputer, /onOpenFile\(file\.id\)/);
  assert.match(portraitComputer, /onOpenReferences\(project\.id\)/);
  assert.match(portraitComputer, /onSetReferenceFilter\(group\.id\)/);
  assert.match(portraitComputer, /href=\{reference\.url\}/);
  assert.match(portraitComputer, /bulletin&&<aside className=\{`portrait-phone-notification/);
  assert.match(portraitComputer, /onPointerDown=\{startNotificationGesture\}[\s\S]*onPointerMove=\{moveNotificationGesture\}[\s\S]*onPointerUp=\{endNotificationGesture\}/);
  assert.match(portraitComputer, /notificationGestureRef\.current\.offset<=-NOTIFICATION_DISMISS_DISTANCE[\s\S]*if\(shouldDismiss\)onDismissBulletin\(\)/, "an upward notification swipe must dismiss after crossing the threshold");
  assert.match(portraitComputer, /portrait-notification-system-icon[\s\S]*computerContent\.bulletin\.notificationHeader/);
  assert.doesNotMatch(portraitComputer, /portrait-notification-dismiss|openNotification|badge=\{bulletin\}/, "system notification must have no close button or Lab Log linkage");
  assert.doesNotMatch(portraitCss, /\.tactile-scene[\s\S]{0,240}animation: none/);
  assert.match(closeups, /const stage=canvas\?\.parentElement/);
  assert.match(closeups, /if\(rect\.width<2\|\|rect\.height<2\)return/);
  assert.match(closeups, /observer\.observe\(stage\)/);
  assert.match(closeups, /layoutFrame=requestAnimationFrame\(resize\)/);
  assert.match(closeups, /isPortrait=rect\.height>=rect\.width/);
  assert.match(closeups, /const shortestSide=Math\.min\(width,height\)/, "portrait closeup sizing must respond to the viewport's shorter side");
  assert.match(closeups, /portraitDistanceScale=isPortrait\?portraitCloseupFitScale\(rect\.width,rect\.height,nextAspect\):1/);
  assert.match(closeups, /isHitAvailable=\(hit:HitMesh\)=>\(!hit\.userData\.requiresOpen\|\|\(drawerTarget>\.5&&drawerProgress>\.72\)\)/, "drawer contents must stop accepting taps as soon as the drawer starts closing");
  assert.match(closeups, /renderer\.setSize\(rect\.width,rect\.height,false\)/);
  assert.match(closeups, /camera\.aspect=nextAspect/);
  assert.match(closeups, /camera\.fov=42/);
  assert.doesNotMatch(closeups, /camera\.fov\s*=\s*isPortrait\s*\?/);
  assert.match(closeups, /sceneCenterShiftX=zone==="books"\?-PORTRAIT_BOOKS_CENTER_X_OFFSET:zone==="notebook"\?PORTRAIT_NOTEBOOK_CENTER_X_OFFSET:0[\s\S]*desired\.x\+=sceneCenterShiftX[\s\S]*desiredTarget\.x\+=sceneCenterShiftX/, "portrait shelf and notebook closeups must use isolated horizontal framing offsets");
  assert.match(closeups, /if\(isPortrait\)\{[\s\S]*drawerDistanceScale=zone==="drawer"\?THREE\.MathUtils\.lerp\(PORTRAIT_DRAWER_CLOSED_DISTANCE_SCALE,PORTRAIT_DRAWER_OPEN_DISTANCE_SCALE,drawerProgress\):1[\s\S]*sceneDistanceScale=zone==="books"\?PORTRAIT_BOOKS_DISTANCE_SCALE:1[\s\S]*multiplyScalar\(portraitDistanceScale\*drawerDistanceScale\*sceneDistanceScale\)[\s\S]*desired\.copy\(desiredTarget\)\.add\(portraitOffset\)/, "portrait bookshelf can move closer without changing the framing of other closeups");
  assert.match(closeups, /drawerCenterShift=PORTRAIT_DRAWER_CENTER_X_OFFSET\*drawerProgress[\s\S]*desired\.x-=drawerCenterShift[\s\S]*desiredTarget\.x-=drawerCenterShift/, "portrait drawer framing must center the open tray without changing desktop framing");
  assert.doesNotMatch(closeups, /portrait(?:Position|Target|Views)|Record<CloseupZone,[^>]+portrait/i);
});

test("editable copy is organized into valid category files", async () => {
  const { readFile } = await import("node:fs/promises");
  for (const name of ["site","intro","room","computer","references","books","drawer","notebook","board","field-case","fax-contact"]) {
    const source = await readFile(new URL(`../content/${name}.json`, import.meta.url), "utf8");
    assert.doesNotThrow(() => JSON.parse(source), `${name}.json must remain valid JSON`);
  }
  const guide = await readFile(new URL("../content/CONTENT_GUIDE.md", import.meta.url), "utf8");
  assert.match(guide, /Website Copy Editing Guide/);
});

test("3D room and layered object exploration remain connected", async () => {
  const game = await import("node:fs/promises").then(({ readFile }) => readFile(new URL("../app/_components/LabGame.tsx", import.meta.url), "utf8"));
  const closeups = await import("node:fs/promises").then(({ readFile }) => readFile(new URL("../app/_components/ZoneCloseup3D.tsx", import.meta.url), "utf8"));
  const page = await import("node:fs/promises").then(({ readFile }) => readFile(new URL("../app/page.tsx", import.meta.url), "utf8"));
  const drawer = await import("node:fs/promises").then(({ readFile }) => readFile(new URL("../content/drawer.json", import.meta.url), "utf8"));
  const drawerMedia = await import("node:fs/promises").then(({ readFile }) => readFile(new URL("../app/_components/drawerArtifactMedia.ts", import.meta.url), "utf8"));
  const notebook = await import("node:fs/promises").then(({ readFile }) => readFile(new URL("../content/notebook.json", import.meta.url), "utf8"));
  const css = await import("node:fs/promises").then(({ readFile }) => readFile(new URL("../public/site.css", import.meta.url), "utf8"));
  const drawerScene = closeups.match(/function buildDrawer[\s\S]*?function buildPrinterDesk/)?.[0] ?? "";
  const notebookScene = page.match(/function NotebookScene[\s\S]*?const boardNotes/)?.[0] ?? "";
  assert.match(game, /WebGLRenderer/);
  assert.match(game, /cameraPoses/);
  assert.match(game, /Raycaster/);
  assert.match(game, /pointermove/);
  assert.match(game, /onInspect/);
  assert.match(game, /faxReady/);
  assert.match(game, /faxPrinted/);
  assert.match(game, /onPrinterInspect/);
  assert.match(game, /room\.faxAlert\.sceneLabel/);
  assert.doesNotMatch(game, /rover/i);
  assert.match(game, /drawer:\s*\[/);
  assert.match(closeups, /WebGLRenderer/);
  assert.match(closeups, /buildBooks/);
  assert.match(closeups, /movie:\$\{movie\.id\}/);
  assert.match(closeups, /hoverOnly=true/);
  assert.match(closeups, /const disc=new THREE\.Mesh\(new THREE\.CylinderGeometry/);
  assert.match(closeups, /MeshPhysicalMaterial/);
  assert.match(closeups, /const clearCase=new THREE\.Mesh\(new RoundedBoxGeometry/);
  assert.match(closeups, /series:higashino/);
  assert.match(closeups, /hoverOnly=!booksContent\.openingEnabled/);
  assert.match(closeups, /item!=="travelMap"&&!fieldCaseContent\.personalDetailsOpeningEnabled/);
  assert.match(closeups, /siteContent\.shared\.comingSoon/);
  assert.match(closeups, /hit\?\.userData\.hoverOnly&&event\.pointerType!=="mouse"/);
  assert.match(closeups, /setHoveredHit\(hit,true\)/);
  assert.match(closeups, /aria-live="polite"/);
  assert.match(closeups, /className="mobile-scene-hotspots"/);
  assert.match(closeups, /guideGroup="books"/);
  assert.match(closeups, /guideGroup="films"/);
  assert.match(closeups, /getWorldPosition\(worldPosition\)[\s\S]*projectedPosition\.multiplyScalar\(1\/visibleHits\.length\)\.project\(camera\)/);
  assert.match(closeups, /touchGuideTimer=window\.setTimeout\(dismissTouchGuide,4200\)/);
  assert.match(closeups, /const visibleHits=markerHits\.filter\(isHitAvailable\)/, "hotspot visibility must follow the same availability rule as hit testing");
  assert.match(closeups, /when those personal close-ups are ready to reopen/);
  assert.doesNotMatch(closeups, /const bookShelf=/);
  assert.doesNotMatch(closeups, /const divider=/);
  assert.match(closeups, /seriesBooks\.map\(\(book,index\)=>makeBook\(book,index,[^\n]+true,false\)\)/);
  assert.match(closeups, /mediaBasket=true/);
  assert.match(closeups, /group\.add\(hit\)/);
  assert.match(closeups, /filmBasket\.rotation\.y=/);
  assert.match(closeups, /movies\.forEach\(\(movie,index\)=>/);
  assert.match(closeups, /const back = roundedBox/);
  assert.match(closeups, /books:\{position:\[[^\]]+\],target:\[[^\]]+\]/);
  assert.match(closeups, /buildDrawer/);
  assert.match(closeups, /monitorScreen/);
  assert.match(closeups, /const monitor=roundedBox/);
  assert.match(drawer, /ALGORITHM REVISION NOTES/);
  assert.match(drawer, /VERSION 01 → VERSION 02/);
  assert.match(drawer, /random selection among courses with remaining capacity/);
  assert.match(drawer, /balance remaining course capacity with remaining student capacity/);
  assert.match(drawer, /More even describes the project goal/);
  assert.match(drawer, /do not establish a formal fairness guarantee/);
  assert.doesNotMatch(drawer, /No method led every criterion/);
  assert.match(drawer, /walk 68\.75% · bus\/subway 47\.92% · bike 37\.5%/);
  assert.match(drawer, /43 valid entries · 46\.51% said time-consuming · 44\.19% said it helped clearly/);
  assert.match(drawer, /32\.56% unclear guidance\/interface · 32\.56% too many features/);
  assert.match(drawer, /one clear walking comfort-zone map with relevant facilities marked, without extra functions or complex navigation/);
  assert.match(drawer, /middle-aged and older residents/);
  assert.match(drawer, /one focused webpage · 5 \/ 10 \/ 15-minute walking comfort zones · clearly marked facilities · no unnecessary features/);
  assert.match(drawer, /"asset": "emg-enclosure-interior"/);
  assert.match(drawer, /"asset": "emg-enclosure-exterior"/);
  assert.doesNotMatch(drawer, /\/archive\//);
  assert.match(drawerMedia, /\.\.\/_assets\/drawer\/\*/);
  assert.match(page, /drawerArtifactMedia\[image\.asset\]/);
  assert.match(page, /className="artifact-media"/);
  assert.match(css, /\.artifact-media \{[^}]*grid-template-columns: repeat\(2,minmax\(0,1fr\)\)/);
  assert.match(css, /\.drawer-document article small \{[^}]*font: clamp\(9px,1\.1vw,11px\)\/1\.55/);
  assert.match(css, /\.drawer-document-return(?:, \.fax-return)? \{[^}]*font: 9px/);
  assert.match(drawerScene, /const cabinetTop=roundedBox/);
  assert.match(drawerScene, /tray\.userData\.drawerTray=true/);
  assert.match(drawerScene, /tray\.add\(bottom,left,right,back,front,inset,handleBar,mountLeft,mountRight\)/);
  assert.match(drawerScene, /workspace\.add\(tray\)/);
  assert.match(drawerScene, /monitorAssembly\.scale\.setScalar\(/);
  assert.match(drawerScene, /buildPrinterModel\(workspace,\[[^\]]+\],[^,]+,faxPrinted\)/);
  assert.match(drawerScene, /addContactCard\(workspace,\[[^\]]+\],[^\n]+\)/);
  assert.equal([...drawerScene.matchAll(/addContactCard\(workspace,/g)].length, 1);
  assert.match(closeups, /buildNotebook/);
  assert.match(closeups, /const table=box\([^\n]+palette\.woodLight/);
  assert.match(closeups, /const matBoard=box/);
  assert.match(closeups, /const researchHit=hitBox\([^\n]+\[left,photo\]\)/);
  assert.doesNotMatch(closeups, /const diagramHit=/);
  assert.match(closeups, /const comparisonSheet=roundedBox/);
  assert.match(closeups, /\[right,comparisonSheet,\.\.\.comparisonBars\]/);
  assert.match(closeups, /const lamp=new THREE\.Group\(\)/);
  assert.match(closeups, /lamp\.position\.set\(/);
  assert.match(closeups, /lamp\.rotation\.y=/);
  assert.match(closeups, /lamp\.scale\.setScalar\(/);
  assert.match(closeups, /lampHead\.add\(shade,reflector,shadeRim,bulb,lampGlow\)/);
  assert.match(closeups, /notebook:\{position:\[[^\]]+\],target:\[[^\]]+\]/);
  assert.match(notebookScene, /model-detail notebook-detail/);
  assert.doesNotMatch(notebookScene, /setReverse|notebook-turn-control/);
  assert.match(notebook, /CLICK THE LEFT OR RIGHT PAGE TO OPEN A NOTE/);
  assert.match(notebook, /ALGORITHM COMPARISON/);
  assert.match(notebook, /First-Come-First-Serve/);
  assert.match(notebook, /Random Ticket/);
  assert.match(notebook, /Probabilistic \+ Maximum Weight/);
  assert.doesNotMatch(notebook, /dossier/i);
  assert.doesNotMatch(notebook, /"diagram"|ALLOCATION REVISION|Residual probability needed a better rule/);
  assert.doesNotMatch(notebook, /TURN IT OVER|TURN THE PAGE|TURN BACK/);
  assert.match(css, /\.model-detail \.notebook-closeup \{[^}]*aspect-ratio: \.79/);
  assert.match(css, /\.model-detail \.notebook-closeup \{[^}]*width: min\(630px,86vw/);
  assert.match(css, /\.notebook-closeup \.paper-return-control \{[^}]*padding: 6px 8px/);
  assert.match(css, /\.notebook-closeup \{[^}]*background-color: #f1e8c9/);
  assert.doesNotMatch(css, /\.notebook-closeup\.turned|\.notebook-turn-control|\.notebook-pipeline/);
  assert.match(closeups, /buildBoard/);
  assert.match(closeups, /boardContent\.hitLabels\[6\]/);
  assert.match(closeups, /const paper=roundedBox\(note\.w,note\.h,/);
  assert.match(css, /\.evidence-card\.note-card \{[^}]*width: min\(450px,86vw\)/);
  assert.match(css, /\.evidence-card\.note-card blockquote \{[^}]*font-size: clamp\(22px,3vw,32px\)/);
  assert.match(closeups, /buildFieldCase/);
  assert.match(closeups, /buildPrinter/);
  assert.match(closeups, /buildContact/);
  assert.match(closeups, /buildPrinterDesk/);
  assert.match(closeups, /contactCardGroup/);
  assert.match(closeups, /contactCardRaised/);
  assert.match(closeups, /RoundedBoxGeometry/);
  assert.match(closeups, /drawerProgress/);
  assert.match(closeups, /drawerWorkspace/);
  assert.match(closeups, /printProgress/);
  assert.match(closeups, /TubeGeometry/);
  assert.match(closeups, /if\(showFax\)/);
  assert.match(closeups, /onFaxPrinted/);
  assert.match(closeups, /fieldCaseContent\.itemLabels\.laserShooting/);
  for (const selector of ["lab-game", "computer-view", "os-screen", "model-scene", "model-detail", "physical-book", "book-turning-sheet", "series-catalog", "contact-reading", "contact-card-detail", "fax-reading", "fax-paper"]) {
    assert.match(css, new RegExp(`\\.${selector}`));
  }
  assert.match(css, /@media \(max-width: 620px\)/);
  assert.match(css, /prefers-reduced-motion/);
  assert.match(css, /contactCardPickup/);
  assert.match(css, /contactCardReturn/);
  assert.match(css, /\.os-window\.is-maximized/);
  assert.match(css, /\.window-controls/);
  assert.match(css, /\.taskbar-app\.active/);
});

test("field case map uses real country geometry instead of hand-drawn continents", async () => {
  const { readFile, readdir } = await import("node:fs/promises");
  const mapSource = await readFile(new URL("../app/_components/fieldCaseMap.ts", import.meta.url), "utf8");
  const photoLibrary = await readFile(new URL("../app/_components/travelPhotoLibrary.ts", import.meta.url), "utf8");
  const page = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  const css = await readFile(new URL("../public/site.css", import.meta.url), "utf8");
  const photoGuide = await readFile(new URL("../app/_assets/travel-map-photos/README.md", import.meta.url), "utf8");
  const nycGuide = await readFile(new URL("../app/_assets/travel-map-photos/new-york-city/ADD-PHOTOS-HERE.md", import.meta.url), "utf8");
  const expectedPhotoCounts = {chongqing:5,kyoto:2,"los-angeles":6,"new-york-city":2,"san-francisco":4,seattle:4,tokyo:2,xian:5};
  for (const [folder,count] of Object.entries(expectedPhotoCounts)) {
    const entries = await readdir(new URL(`../app/_assets/travel-map-photos/${folder}/`, import.meta.url), {withFileTypes:true});
    assert.equal(entries.filter((entry) => entry.isFile() && /\.(?:jpe?g|png|webp|gif|avif)$/i.test(entry.name)).length, count, `${folder} photo count`);
  }
  const countries = JSON.parse(await readFile(new URL("../app/_components/worldCountries110m.json", import.meta.url), "utf8"));
  assert.ok(countries.length >= 170, "the map should retain Natural Earth country coverage");
  assert.ok(countries.every((country) => country.g?.type === "Polygon" || country.g?.type === "MultiPolygon"));
  assert.match(mapSource, /fill\("evenodd"\)/);
  assert.match(mapSource, /\[-width,0,width\]/);
  assert.match(mapSource, /FIELD_CASE_TRAVEL_PINS/);
  assert.match(mapSource, /FIELD_CASE_MAP_VIEWS/);
  assert.match(mapSource, /worldGroup/);
  assert.match(mapSource, /camera\.zoom<2\.25/);
  for (const place of ["Seattle", "San Francisco", "Los Angeles", "San Diego", "New York City", "Philadelphia", "Boston", "Orlando", "Busan", "Bangkok", "Chongqing", "Xi'an", "Shanghai", "Kyoto", "Tokyo", "Beijing", "Macau", "Qingdao", "Dalian", "Beihai", "Lijiang"]) {
    assert.match(mapSource, new RegExp(place.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")));
  }
  assert.doesNotMatch(mapSource, /name:"(?:Nanjing|Suzhou|Yixing)"/);
  assert.equal([...mapSource.matchAll(/\{name:"/g)].length, 21);
  assert.equal([...mapSource.matchAll(/country:"/g)].length, 21);
  assert.equal([...mapSource.matchAll(/photoFolder:"/g)].length, 21);
  assert.equal([...mapSource.matchAll(/region:"asia"/g)].length, 13);
  const worldGroups = [...mapSource.matchAll(/worldGroup:"([^"]+)"/g)].map((match) => match[1]);
  assert.equal(new Set(worldGroups).size, 19);
  assert.match(mapSource, /name:"Seattle"[^\n]+worldGroup:"seattle"/);
  assert.match(mapSource, /name:"Los Angeles"[^\n]+worldGroup:"southern-california"/);
  assert.match(mapSource, /name:"San Diego"[^\n]+worldGroup:"southern-california"/);
  assert.match(mapSource, /name:"Busan"[^\n]+country:"South Korea"[^\n]+worldGroup:"busan"/);
  assert.match(mapSource, /name:"Kyoto"[^\n]+country:"Japan"[^\n]+worldGroup:"kyoto"/);
  assert.doesNotMatch(mapSource, /name:"Osaka"|photoFolder:"osaka"/);
  assert.doesNotMatch(mapSource, /japan-korea|usa-west/);
  const mapReading = page.match(/function FieldMapReading[\s\S]*?\r?\n}\r?\n\r?\nfunction FieldCaseScene/)?.[0] ?? "";
  assert.match(mapReading, /onWheel/);
  assert.match(mapReading, /setPointerCapture/);
  assert.match(mapReading, /field-map-views/);
  assert.match(mapReading, /travelPhotosForPin/);
  assert.match(mapReading, /field-map-memory/);
  assert.match(mapReading, /aria-labelledby="field-map-memory-title"/);
  assert.match(mapReading, /field-map-photo-stage is-/);
  assert.match(mapReading, /photoCloseRef/);
  assert.match(mapReading, /tabIndex=\{0\}/);
  assert.match(mapReading, /preloadTravelPhoto/);
  assert.match(mapReading, /image\.decode\(\)/);
  assert.match(mapReading, /FIELD_CASE_TRAVEL_PINS/);
  assert.match(mapReading, /aria-busy=\{photoStatus==="loading"\}/);
  assert.match(mapReading, /field-map-photo-loading/);
  assert.match(mapReading, /activePhotoSrcRef/);
  assert.match(mapReading, /decodedPhotoSrcRef/);
  assert.match(mapReading, /photoImageCacheRef/);
  assert.match(mapReading, /photoImageCacheRef\.current\.set\(photo\.src,image\)/);
  assert.match(mapReading, /decodedPhotoSrcRef\.current\.add\(photo\.src\)/);
  assert.match(mapReading, /decodedPhotoSrcRef\.current\.add\(expectedSrc\)/);
  assert.match(mapReading, /decodedPhotoSrcRef\.current\.has\(nextPhoto\.src\)/);
  assert.match(mapReading, /decodedPhotoSrcRef\.current\.delete\(currentPhoto\.src\)/);
  assert.match(mapReading, /navigationLockedRef/);
  assert.match(mapReading, /await image\.decode\(\)/);
  assert.doesNotMatch(mapReading, /void image\.decode\(\)/);
  assert.match(mapReading, /Promise\.all\(warmups\)/);
  assert.match(mapReading, /photoImageCache\.forEach/);
  assert.match(mapReading, /photoImageCache\.clear\(\)/);
  assert.match(mapReading, /decodedPhotoSrcs\.clear\(\)/);
  assert.match(mapReading, /image\.onload=null/);
  assert.match(mapReading, /image\.onerror=null/);
  assert.doesNotMatch(mapReading, /TravelPhotoLayout|photoLayout|layoutForAspect/);
  assert.doesNotMatch(mapReading, /--photo-aspect|--photo-frame-width/);
  assert.match(mapReading, /Previous photo/);
  assert.match(mapReading, /Next photo/);
  assert.match(mapReading, /randomLostTravelMessage/);
  assert.match(photoLibrary, /import\.meta\.glob/);
  assert.match(photoLibrary, /photoFolder/);
  assert.match(photoLibrary, /localeCompare/);
  assert.doesNotMatch(page, /manifest\.json/);
  assert.match(css, /\.field-map-memory/);
  assert.match(css, /\.field-map-memory \{[^}]*720px[^}]*115\.2svh - 281px/);
  assert.match(css, /\.field-map-memory \{[^}]*aspect-ratio: 720 \/ 625/);
  assert.match(css, /\.field-map-memory \{[^}]*grid-template: auto minmax\(0,1fr\) auto \/ minmax\(0,1fr\)/);
  assert.match(css, /\.field-map-memory \{[^}]*background-color: #ded2ad/);
  assert.match(css, /animation: fieldMapMemoryIn/);
  assert.match(css, /\.field-map-memory > header, \.field-map-photo-stage, \.field-map-memory > footer \{[^}]*min-width: 0[^}]*max-width: 100%/);
  assert.match(css, /\.field-map-memory > header \{[^}]*min-height: 54px[^}]*padding: 7px 2px 6px 5px[^}]*border-bottom:/);
  assert.match(css, /\.field-map-memory > header > div \{[^}]*transform: translateY\(2px\)/);
  assert.match(css, /\.field-map-memory > header h2 \{[^}]*padding-bottom: 5px[^}]*font: 24px\/1 "Segoe Print",cursive/);
  assert.match(css, /\.field-map-photo-stage \{[^}]*display: flex/);
  assert.match(css, /\.field-map-photo-stage \{[^}]*width: auto[^}]*height: auto/);
  assert.match(css, /\.field-map-photo-stage \{[^}]*padding: 0/);
  assert.doesNotMatch(css, /\.field-map-photo-stage \{[^}]*(?:aspect-ratio|grid-template-columns):/);
  assert.match(css, /\.field-map-photo-stage > img \{[^}]*object-fit: contain/);
  assert.match(css, /\.field-map-photo-stage > img \{[^}]*width: 100%[^}]*height: 100%/);
  assert.match(css, /\.field-map-photo-stage > img \{[^}]*min-width: 0[^}]*max-width: 100%[^}]*max-height: 100%/);
  assert.doesNotMatch(css, /\.field-map-photo-stage > img \{[^}]*max-width: none/);
  assert.match(css, /\.field-map-photo-stage\.is-loading > img \{[^}]*filter: blur/);
  assert.match(css, /\.field-map-photo-stage\.is-loading > img \{[^}]*opacity: 1/);
  assert.doesNotMatch(css, /\.field-map-photo-stage\.is-loading > img \{[^}]*transform:/);
  assert.match(css, /\.field-map-photo-loading, \.field-map-photo-message \{[^}]*position: absolute/);
  assert.match(css, /\.field-map-photo-stage \{[^}]*border: 0/);
  assert.match(css, /\.field-map-photo-stage \{[^}]*background: transparent/);
  assert.match(css, /\.field-map-photo-stage \{[^}]*box-shadow: none/);
  assert.match(css, /\.field-map-photo-loading \{[^}]*background: transparent/);
  assert.match(css, /\.field-map-photo-message\.lost \{[^}]*background: transparent/);
  assert.match(css, /\.field-map-photo-loading i \{[^}]*rgba\(79,70,48,.28\)/);
  assert.doesNotMatch(css, /\.field-map-photo-stage \{[^}]*background: #293732/);
  assert.doesNotMatch(css, /\.field-map-photo-message\.lost \{[^}]*background: #f2ead3/);
  assert.doesNotMatch(css, /\.field-map-photo-loading i \{[^}]*rgba\(246,237,211,.4\)/);
  assert.doesNotMatch(css, /\.field-map-photo-stage \{[^}]*inset 0 0 0 5px/);
  assert.doesNotMatch(css, /\.field-map-photo-stage \{[^}]*3px 5px/);
  assert.match(css, /padding: 15px 15px 12px/);
  assert.match(css, /padding: 12px 12px 10px/);
  assert.match(css, /@media \(max-width: 620px\)[\s\S]*\.field-map-memory \{[^}]*714px[^}]*100svh - 104px[^}]*100vw \+ 90px/);
  assert.match(css, /@media \(max-width: 620px\)[\s\S]*\.field-map-photo-stage \{[^}]*padding: 0/);
  assert.match(css, /@media \(max-height: 500px\) and \(min-width: 621px\)[\s\S]*\.field-map-memory \{[^}]*115\.2svh - 184px[^}]*max-height: calc\(100% - 32px\)/);
  assert.doesNotMatch(css, /--photo-aspect|--photo-frame-width/);
  assert.doesNotMatch(css, /\.field-map-photo-stage\.is-(?:loading|ready|lost)[^{]*\{[^}]*(?:width|height|padding|margin|aspect-ratio):/);
  assert.doesNotMatch(css, /\.field-map-memory\.is-photo-ready/);
  assert.doesNotMatch(css, /field-map-photo-stage:not\(\.is-ready\)/);
  assert.match(photoGuide, /You do not need to modify any code/);
  assert.match(nycGuide, /new-york-city/);
  assert.doesNotMatch(mapReading, /item\.copy|field-map-places|object-tags/);
  assert.doesNotMatch(mapSource, /landMasses/);
});
